---
packageList:
  - netcat
  - bindutils
templates:
- localLocation: /tmp/testmytemplate.tpl
  remoteLocation: https://s3.amazonaws.com/somebucket/testtemplate.tpl
  vars:
    type: command
    output: dd if=/dev/urandom bs=5 count=1
    variable: REPLACE_ME_1
- localLocation: /tmp/testanothertemplate.tpl
  remoteLocation: https://s3.amazonaws.com/somebucket/testtemplate2.tpl
  vars:
    type: value
    output: FOOTHEBARBAZ
    variable: REPLACE_ME_2
services:
- name: nginx
  setEnabled: yes
  state: started
  restartTrigger:
    - /tmp/testmytemplate.tpl
  restartAlways: no
- name: apache
  setEnabled: yes
  state: started
  restartTrigger:
    - /tmp/testmytemplate.tpl
  restartAlways: no