---
tempDirectory: /tmp/bruce
preExecCmds:
  - echo 'hi there' > /tmp/logExample
packageList:
  - netcat
  - bind-utils|apt=bind9-utils
templates:
- localLocation: /tmp/local_template_1.tpl
  perms: 0664
  owner: whattingh
  group: whattingh
  remoteLocation: ./examples/test_template_1.yml
  vars:
  - type: command
    output: /usr/bin/ls -alh /tmp/bruce/
    variable: REPLACE_ME_1
  - type: value
    output: hi there
    variable: REPLACE_ME_2
- localLocation: /tmp/local_template_2.tpl
  remoteLocation: ./examples/test_template_2.yml
  owner: whattingh
  group: whattingh
  perms: 0664
  vars:
  - type: value
    output: FOOTHEBARBAZ
    variable: REPLACE_ME_2
services:
- name: nginx
  setEnabled: yes
  state: started
  restartTrigger:
    - /tmp/local_template_1.tpl
  failRevertTemplate:
    - /tmp/local_template_1.tpl
  restartAlways: no
- name: apache
  setEnabled: yes
  state: started
  restartTrigger:
    - /tmp/local_template_2.tpl
  restartAlways: no
postExecCmds:
  - echo "completed execution" > /tmp/logExample