---
# this is a temporary directory where bruce will create / store templates for execution etc
tempDirectory: /tmp/bruce
steps:
  - name: testCommand
    cmd: echo "Hello World"
  - name: nginx main conf
    template: /tmp/nginx.conf
    remoteLocation: https://raw.githubusercontent.com/Nitecon/bruce/main/examples/nginx/templates/etc/nginx/nginx.conf
    perms: 0664
    owner: root
    group: root
    vars:
      - type: value
        input: nginx|apt=www-data  # uses nginx for all platforms that don't use apt installer on those use www-data
        variable: NGINX_USER
  - name: install packages for ubuntu distros
    packageList:
      - bind9-utils
    osLimits: ubuntu:20.04|debian
  - name: install packages for rh distros
    packageList:
      - bind-utils
    osLimits: fedora|redhat|centos|arch
  - name: set ownership of files
    type: file
    path: /tmp/nginx.conf
    owner: nginx
    group: nginx
    recursive: false
  - name: set nginx enabled
    service: nginx
    setEnabled: true
    state: started # can be started / stopped
    restartTrigger: # if these templates were altered always restart
      - /tmp/nginx.conf
    restartAlways: false
    osLimits: all
  - name: Send hup to nginx
    pidFile: /var/run/nginx.pid
    signal: SIGHUP #currently only supports: SIGHUP / SIGINT

