---
## Steps are an array of operators that can be used to mutate the environment
## the current list of operators include:
## Command: enables the ability to run an arbitrary command on the system and limit the command based on specific OS
## Ownership: Ability to chown individual / recursive directories of files
## Packages: Ability to install packages based on the locally supported os installer like dnf / yum / apt-get
## Services: Ability to enable / restart and reconfigure and restart services based on template updates
## Signals: Ability to send a signal to a particular process
## Templates: Ability to create templates on the system and inject variables by values from commands or provided input data.
##
## Some examples of operators as steps are shown below, see documentation on how to use.
steps:
  - name: testCommand
    cmd: echo "Hello World"
  - name: nginx main conf
    template: /tmp/nginx.conf
    remoteLocation: https://raw.githubusercontent.com/Nitecon/bruce/main/examples/nginx/templates/etc/nginx/nginx.conf
    perms: 0664
    owner: root
    group: root
    vars:
      - type: value
        input: nginx|apt=www-data  # uses nginx for all platforms that don't use apt installer on those use www-data
        variable: NGINX_USER
  - name: install packages for ubuntu distros
    packageList:
      - bind9-utils
    osLimits: ubuntu:20.04|debian
  - name: install packages for rh distros
    packageList:
      - bind-utils
    osLimits: fedora|redhat|centos|arch
  - name: set ownership of files
    type: file
    path: /tmp/nginx.conf
    owner: nginx
    group: nginx
    recursive: false
  - name: set nginx enabled
    service: nginx
    setEnabled: true
    state: started # can be started / stopped
    restartTrigger: # if these templates were altered always restart
      - /etc/nginx/nginx.conf
    restartAlways: false
    osLimits: all
  - name: Send hup to nginx # this will be altered to include restartTrigger to watch templates like services.
    pidFile: /var/run/nginx.pid
    signal: SIGHUP #currently only supports: SIGHUP / SIGINT

